title: Keith T. Butler
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://keeeto.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
kramdown:
  highlighter: rouge
  input: GFM
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Publications
   url: https://scholar.google.com/citations?user=eruLmgUAAAAJ&hl=en
 - title: Materials Hipster
   url: /tag/materials_hipster
 - title: Materials Hipster
   url: https://github.com/keeeto/keeeto.github.io

social:
   github: keeeto
   twitter: keeeto2000
   email: keith.butler@stfc.ac.uk

google_analytics: "UA-113215636-1"
