title: Keith T. Butler
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://keeeto.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: keeeto
   twitter: keeeto2000
   email: keith.butler@stfc.ac.uk

google_analytics: "UA-113215636-1"
